
import { QuestionnaireProvider } from "@/Provider/context";
import "./globals.css";
import "@/assets/css/bootstrap/bootstrap.min.css"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <QuestionnaireProvider>
          {children}
        </QuestionnaireProvider>
      </body>
    </html>
  );
}
